#!/usr/bin/env bash
# This script:
# Creates the file /var/run/bestscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/bestscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

FILE="/var/run/bestscript.pid"
echo "$$" > $FILE

trap "rm /var/run/bestscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; rm /var/run/bestscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
